# Generated by Django 2.2.7 on 2019-11-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
