# Generated by Django 2.2.7 on 2019-11-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191110_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
